In [1]:
import numpy as np

In [3]:

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [4]:

subarray1 = matrix[0:2, 1:3]
subarray2 = matrix[:, 1]
subarray3 = matrix[1, :]

print("Subarray 1:")
print(subarray1)
print("Subarray 2:")
print(subarray2)
print("Subarray 3:")
print(subarray3)

Subarray 1:
[[2 3]
 [5 6]]
Subarray 2:
[2 5 8]
Subarray 3:
[4 5 6]


#3D array


In [5]:
array_3d = np.array([[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]]])

In [6]:
subarray1 = array_3d[0, :, :]
subarray2 = array_3d[:, 1, :]
subarray3 = array_3d[:, :, 2]

print("Subarray 1:")
print(subarray1)
print("Subarray 2:")
print(subarray2)
print("Subarray 3:")
print(subarray3)

Subarray 1:
[[1 2 3]
 [4 5 6]]
Subarray 2:
[[ 4  5  6]
 [10 11 12]]
Subarray 3:
[[ 3  6]
 [ 9 12]]
